<?php
/**
 * 2000-2012 FIA-NET
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please contact us
 * via http://www.fia-net-group.com/formulaire.php so we can send you a copy immediately.
 *
 *  @author FIA-NET <support-boutique@fia-net.com>
 *  @copyright 2000-2012 FIA-NET
 *  @version Release: $Revision: 1.0.1 $
 *  @license http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Shipping type'); ?></h3></td>
            <td class="a-right">
                <button id="1021" type="button" class="scalable save" onclick="editForm.submit();" style=""><span><?php echo $this->__('Save'); ?></span></button>
            </td>
        </tr>
    </table>
</div>
<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Shipping methods list'); ?></h4>
<div class="entry-edit">
    <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post'); ?>">
        <?php echo $this->getBlockHtml('formkey') ?>
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <th><?php echo $this->__('Shipping method'); ?></th>
                    <th><?php echo $this->__('FIA-NET Shipping type'); ?></th>
                    <th><?php echo $this->__('Shipping speed'); ?></th>
                    <th><?php echo $this->__('Conveyor'); ?></th>
                </tr>
                <?php
                $shipping_list = $this->shipping;
                $ShippingType = Mage::getModel("sac/source_shippingtype")->toOptionArray();
                $DeliveryTimes = Mage::getModel("sac/source_deliverytimes")->toOptionArray();
                foreach ($shipping_list as $Code => $label) {
                    $current_shipping = Mage::getModel('fianet/shipping_association')->load($Code);
                    echo '<tr>';
                    echo '<td class="label">' . $label . '</td>';
                    echo '<td class="input-ele"><select name="' . $Code . '[shippingType]">';
                    foreach ($ShippingType as $data) {
                        $sel = '';
                        if ($current_shipping->shipping_code == null && $data['value'] == '4') {
                            $sel = ' selected';
                        } elseif ($current_shipping->shipping_code != null) {
                            $sel = $current_shipping->fianet_shipping_type == $data['value'] ? ' selected' : '';
                        }
                        echo '<option value="' . $data['value'] . '"' . $sel . '>' . $data['label'] . '</option>';
                    }
                    echo '</select></td>';
                    echo '<td class="input-ele"><select name="' . $Code . '[deliveryTimes]">';
                    foreach ($DeliveryTimes as $data) {
                        $sel = '';
                        if ($current_shipping->shipping_code == null && $data['value'] == '2') {
                            $sel = ' selected';
                        } elseif ($current_shipping->shipping_code != null) {
                            $sel = $current_shipping->delivery_times == $data['value'] ? ' selected' : '';
                        }
                        echo '<option value="' . $data['value'] . '"' . $sel . '>' . $data['label'] . '</option>';
                    }
                    echo '</select></td>';
                    $val = $current_shipping->shipping_code == null ? $this->__('To define') : $current_shipping->conveyor_name;
                    echo '<td class="input-ele">
			<input type="text" name="' . $Code . '[conveyorName]" value="' . $val . '"></td>';
                    echo '</tr>';
                }
                ?>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form', '');
</script>